# Generated by Django 3.1.5 on 2021-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
