# Generated by Django 3.1.5 on 2021-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
