# Generated by Django 3.1.5 on 2021-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210125_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='firstname',
            field=models.CharField(default='Error', max_length=100),
        ),
        migrations.AddField(
            model_name='follow',
            name='lastname',
            field=models.CharField(default='Error', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
