# Generated by Django 3.1.5 on 2021-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210130_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
